[build]
  command = "npm run build"        # Or the correct build command for your framework
  publish = "dist"                 # Or "build" if your framework outputs here

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200